from __future__ import annotations

from typing import Any

DEFAULT_CRAWLER_SOURCES: list[dict[str, Any]] = [
    {
        "category": "bidding",
        "name": "结构化标讯接口（当前主链路）",
        "url": "https://customer.jianyu360.com/",
        "selectors": {
            "type": "api",
            "protected": True,
            "scope": "已授权结构化标讯数据",
            "strategy": "当前主链路：按管理后台关键词检索，入库后做相关性评分、金额抽取和线索确认",
        },
        "is_active": True,
    },
    {
        "category": "bidding",
        "name": "中国政府采购网",
        "url": "https://www.ccgp.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "国家级政府采购公告、中标/成交、合同等",
            "strategy": "候选标讯源：审核后按关键词低频检索，遵守 robots、限速和失败退避",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中央政府采购网",
        "url": "https://www.zycg.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "中央国家机关采购公告、结果公告、工程采购等",
            "strategy": "候选标讯源：审核后低频采集，优先检索信息化、数据、地图、空间智能相关公告",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "全国公共资源交易平台",
        "url": "https://www.ggzy.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "全国公共资源交易公开信息，含政府采购与工程建设交易公告/结果公示",
            "strategy": "候选标讯源：审核后按业务类型和关键词低频采集，先入候选池再评分",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中国招标投标公共服务平台",
        "url": "http://www.cebpubservice.com/",
        "selectors": {
            "type": "official_site",
            "scope": "依法必须招标项目公告、公示与结果信息",
            "strategy": "候选标讯源：审核后只采集招标公告、中标候选人/结果等公开信息",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "广东省政府采购网",
        "url": "https://gdgpo.czt.gd.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "广东省政府采购公告、结果、合同等",
            "strategy": "候选标讯源：重点关注政数、公安、自然资源、数据治理与空间智能项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "广东省招标投标监管网",
        "url": "https://zbtb.gd.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "广东省招标投标公告、公示与监管信息",
            "strategy": "候选标讯源：审核后低频抓取，优先保留数字政府和公共服务信息化项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "北京市公共资源交易服务平台",
        "url": "https://ggzyfw.beijing.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "北京市公共资源交易、政府采购、工程建设公告公示",
            "strategy": "候选标讯源：审核后低频采集，按关键词过滤泛工程项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "江苏政府采购网",
        "url": "https://www.ccgp-jiangsu.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "江苏省政府采购公告、结果、合同等",
            "strategy": "候选标讯源：审核后低频采集，重点关注公安、自然资源、政务数据项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "江苏省公共资源交易平台",
        "url": "https://jsggzy.jszwfw.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "江苏省公共资源交易公告、公示、结果信息",
            "strategy": "候选标讯源：审核后按业务类型和关键词低频采集",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "国家电网新一代电子商务平台",
        "url": "https://ecp.sgcc.com.cn/ecp2.0/portal/",
        "selectors": {
            "type": "browser",
            "scope": "国家电网采购公告、招标公告、结果公示等",
            "strategy": "候选标讯源：审核后采用低频渲染采集，重点关注电力数据、地图、空间、Agent相关项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "南方电网供应链统一服务平台",
        "url": "https://www.bidding.csg.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "南方电网招标采购公告、结果公示等",
            "strategy": "候选标讯源：审核后低频采集，重点关注电力数字化、数据治理、空间智能场景",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中国移动电子采购与招投标系统",
        "url": "https://es.b2b.10086.cn/newbid/",
        "selectors": {
            "type": "browser",
            "scope": "中国移动采购公告、结果公告、供应商相关信息",
            "strategy": "候选标讯源：审核后低频渲染采集，只关注运营商数据、地图、空间智能和AI相关项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中国联通合作方门户",
        "url": "https://www.cuecp.cn/",
        "selectors": {
            "type": "browser",
            "scope": "中国联通采购、招标、合作方相关公开信息",
            "strategy": "候选标讯源：审核后低频渲染采集，重点关注运营商数字化与AI项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中国电信阳光采购网",
        "url": "https://caigou.chinatelecom.com.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "中国电信招标、比选、询价、采购结果等公开公告",
            "strategy": "候选标讯源：审核后低频采集，重点关注运营商数据治理、地图、AI与Agent场景",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "国家数据局",
        "url": "https://www.nda.gov.cn/sjj/zwgk/",
        "base_url": "https://www.nda.gov.cn",
        "selectors": {
            "type": "direct_pages",
            "protected": True,
            "scope": "国家数据局政策发布、通知公告、数据要素和公共数据政策",
            "strategy": "内置政策源：按自然年采集重点政策，保留与公安/政数/大数据/地址/空间/Agent相关内容",
        },
        "is_active": True,
    },
    {
        "category": "policy",
        "name": "国家发展改革委政务公开",
        "url": "https://www.ndrc.gov.cn/xxgk/",
        "base_url": "https://www.ndrc.gov.cn",
        "selectors": {
            "type": "http",
            "protected": True,
            "scope": "数字经济、数据要素、公共数据和产业政策公开信息",
            "strategy": "内置政策源：低频采集公开列表，按年度和业务关键词过滤",
        },
        "is_active": True,
    },
    {
        "category": "policy",
        "name": "自然资源部通知公告",
        "url": "https://www.mnr.gov.cn/gk/tzgg/",
        "base_url": "https://www.mnr.gov.cn",
        "selectors": {
            "type": "http",
            "protected": True,
            "scope": "自然资源、测绘地理信息、实景三维、空间数据政策通知",
            "strategy": "内置政策源：低频采集公开列表，按年度和业务关键词过滤",
        },
        "is_active": True,
    },
    {
        "category": "policy",
        "name": "重庆市人民政府",
        "url": "https://www.cq.gov.cn/zwgk/",
        "base_url": "https://www.cq.gov.cn",
        "selectors": {
            "type": "direct_pages",
            "protected": True,
            "scope": "地方数字政府、城市治理、公共数据政策",
            "strategy": "内置政策源：按年度直采重点公开页面，命中业务关键词后入库",
        },
        "is_active": True,
    },
    {
        "category": "policy",
        "name": "北京市政务服务和数据管理局",
        "url": "https://zwfwj.beijing.gov.cn/",
        "base_url": "https://zwfwj.beijing.gov.cn",
        "selectors": {
            "type": "direct_pages",
            "protected": True,
            "scope": "北京政务服务、数据管理、数字政府相关政策",
            "strategy": "内置政策源：按年度直采重点公开页面，命中业务关键词后入库",
        },
        "is_active": True,
    },
    {
        "category": "news",
        "name": "自然资源部",
        "url": "http://www.mnr.gov.cn/dt/ywbb/",
        "base_url": "http://www.mnr.gov.cn/dt/ywbb/",
        "selectors": {
            "type": "http",
            "protected": True,
            "scope": "自然资源、实景三维、空间数据、地理信息相关市场动态",
            "strategy": "内置市场线索源：低频采集公开列表，按公安/政数/地址/地图/空间/Agent关键词过滤",
        },
        "is_active": True,
    },
    {
        "category": "news",
        "name": "福建省数据管理局",
        "url": "https://fgw.fujian.gov.cn/ztzl/szfjzt/",
        "base_url": "https://fgw.fujian.gov.cn",
        "selectors": {
            "type": "direct_pages",
            "protected": True,
            "scope": "地方数字化、公共数据、数据要素和政务数据动态",
            "strategy": "内置市场线索源：按年度直采重点公开页面，命中业务关键词后入库",
        },
        "is_active": True,
    },
    {
        "category": "news",
        "name": "锡林郭勒盟行政公署",
        "url": "https://www.xlgl.gov.cn/",
        "base_url": "https://www.xlgl.gov.cn",
        "selectors": {
            "type": "direct_pages",
            "protected": True,
            "scope": "地方政务数字化、基层治理、公共数据相关动态",
            "strategy": "内置市场线索源：按年度直采重点公开页面，命中业务关键词后入库",
        },
        "is_active": True,
    },
    {
        "category": "competitor",
        "name": "超图软件",
        "url": "https://www.supermap.com/cn/",
        "base_url": "https://www.supermap.com",
        "selectors": {
            "type": "official_site",
            "scope": "竞对官网新闻、案例、产品动态和区域动作",
            "strategy": "候选竞对源：审核后低频采集，按中标/案例/产品/合作/区域扩张分类研判",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "中地数码 MapGIS",
        "url": "https://www.mapgis.com/",
        "base_url": "https://www.mapgis.com",
        "selectors": {
            "type": "official_site",
            "scope": "竞对官网新闻、案例、产品动态和区域动作",
            "strategy": "候选竞对源：审核后低频采集，按中标/案例/产品/合作/区域扩张分类研判",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "航天宏图",
        "url": "https://www.piesat.cn/",
        "base_url": "https://www.piesat.cn",
        "selectors": {
            "type": "official_site",
            "scope": "竞对官网新闻、案例、产品动态和区域动作",
            "strategy": "候选竞对源：审核后低频采集，按中标/案例/产品/合作/区域扩张分类研判",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "数字政通",
        "url": "https://www.egova.com.cn/",
        "base_url": "https://www.egova.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "竞对官网新闻、案例、产品动态和区域动作",
            "strategy": "候选竞对源：审核后低频采集，按中标/案例/产品/合作/区域扩张分类研判",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "36氪",
        "url": "https://36kr.com/feed",
        "selectors": {
            "type": "rss",
            "protected": True,
            "scope": "AI Agent、空间数据、GIS/时空智能和产业动态订阅源",
            "strategy": "内置行业知识源：订阅解析，按AI Agent、空间数据、地址治理和时空智能关键词过滤后入库",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "Solidot",
        "url": "https://www.solidot.org/index.rss",
        "selectors": {
            "type": "rss",
            "protected": True,
            "scope": "开源、AI、空间数据工具链和技术趋势订阅源",
            "strategy": "内置行业知识源：订阅解析，按AI Agent、空间数据、GIS和时空智能关键词过滤后入库",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "InfoQ中文",
        "url": "https://www.infoq.cn/feed",
        "selectors": {
            "type": "rss",
            "protected": True,
            "scope": "企业技术、AI工程化、空间数据工程和架构实践订阅源",
            "strategy": "内置行业知识源：订阅解析，沉淀可用于产品、售前和空间数据方案的技术素材",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "机器之心",
        "url": "https://www.jiqizhixin.com/",
        "base_url": "https://www.jiqizhixin.com",
        "selectors": {
            "type": "http",
            "protected": True,
            "scope": "AI研究、产业应用、模型、Agent和空间智能相关动态",
            "strategy": "内置行业知识源：低频网页采集，标题必须命中核心AI Agent或空间数据关键词",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "量子位",
        "url": "https://www.qbitai.com/category/资讯",
        "base_url": "https://www.qbitai.com",
        "selectors": {
            "type": "http",
            "protected": True,
            "scope": "AI产品、空间数据行业应用、位置智能和技术趋势动态",
            "strategy": "内置行业知识源：低频网页采集，标题必须命中核心AI Agent或空间数据关键词",
        },
        "is_active": True,
    },
]


DEFAULT_CRAWLER_SOURCES.extend([
    # 标讯候选源：默认不启用，审核抓取策略后再接入。
    {
        "category": "bidding",
        "name": "上海政府采购网",
        "url": "https://www.ccgp-shanghai.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "上海市政府采购公告、结果公告、合同公告等",
            "strategy": "候选标讯源：审核后按公安、政数、地址治理、空间智能关键词低频采集",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "浙江政府采购网",
        "url": "https://zfcg.czt.zj.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "浙江省政府采购公告、采购结果和合同信息",
            "strategy": "候选标讯源：重点关注数字政府、公共数据、自然资源和公安信息化项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "山东政府采购网",
        "url": "http://www.ccgp-shandong.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "山东省政府采购公告、成交/中标结果等",
            "strategy": "候选标讯源：审核后低频采集，先按关键词过滤再入标讯候选池",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "四川政府采购网",
        "url": "https://www.ccgp-sichuan.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "四川省政府采购公告、结果和更正信息",
            "strategy": "候选标讯源：重点关注公安、政数、数据治理、地图和三维项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "湖北政府采购网",
        "url": "https://www.ccgp-hubei.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "湖北省政府采购公告和结果信息",
            "strategy": "候选标讯源：审核后低频采集，适合作为华中区域重点监控源",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "安徽政府采购网",
        "url": "https://www.ccgp-anhui.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "安徽省政府采购公告、结果和合同信息",
            "strategy": "候选标讯源：审核后按业务关键词低频采集并做相关性评分",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "福建省政府采购网",
        "url": "https://zfcg.czt.fujian.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "福建省政府采购公告、结果公告和合同信息",
            "strategy": "候选标讯源：重点关注数字福建、数据局、自然资源和公安项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "河南省政府采购网",
        "url": "https://www.hngp.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "河南省政府采购公告、结果和意向公开",
            "strategy": "候选标讯源：审核后低频采集，按业务关键词进入候选池",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "河北省政府采购网",
        "url": "http://www.ccgp-hebei.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "河北省政府采购公告、结果公告和合同信息",
            "strategy": "候选标讯源：审核后低频采集，重点过滤泛硬件和装修类项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "重庆市政府采购网",
        "url": "https://www.ccgp-chongqing.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "重庆市政府采购公告、结果和采购意向",
            "strategy": "候选标讯源：重点关注基层智治、城市治理和政务数据项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "上海市公共资源交易中心",
        "url": "https://www.shggzy.com/",
        "selectors": {
            "type": "official_site",
            "scope": "上海公共资源交易公告、公示和交易结果",
            "strategy": "候选标讯源：审核后只采集信息化、数据、地图、空间智能相关公告",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "浙江省公共资源交易服务平台",
        "url": "https://ggzy.zj.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "浙江公共资源交易公告、公示和结果信息",
            "strategy": "候选标讯源：审核后按区域和业务关键词低频采集",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "四川省公共资源交易信息网",
        "url": "https://ggzyjy.sc.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "四川公共资源交易公告、公示和交易结果",
            "strategy": "候选标讯源：审核后低频采集，重点关注政务和公共安全信息化项目",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "湖北省公共资源交易电子服务系统",
        "url": "https://www.hbggzyfwpt.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "湖北公共资源交易公告、公示和结果信息",
            "strategy": "候选标讯源：审核后低频采集，适合作为湖北区域重点监控源",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "福建省公共资源交易电子公共服务平台",
        "url": "https://ggzyfw.fujian.gov.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "福建公共资源交易公告、公示和交易结果",
            "strategy": "候选标讯源：审核后低频采集，按关键词过滤泛工程类公告",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "江西省公共资源交易平台",
        "url": "https://www.jxsggzy.cn/",
        "selectors": {
            "type": "official_site",
            "scope": "江西公共资源交易公告、公示和交易结果",
            "strategy": "候选标讯源：审核后低频采集，先进入候选池再做相关性评分",
        },
        "is_active": False,
    },
    # 政策候选源：默认不启用，适合按专题逐步接入。
    {
        "category": "policy",
        "name": "工业和信息化部政策文件",
        "url": "https://www.miit.gov.cn/zwgk/zcwj/",
        "base_url": "https://www.miit.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "工业互联网、人工智能、软件和信息技术服务业政策",
            "strategy": "候选政策源：审核后按自然年和关键词采集AI、数据治理、智能体相关政策",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "国家能源局政府信息公开",
        "url": "https://zfxxgk.nea.gov.cn/",
        "base_url": "https://zfxxgk.nea.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "能源数字化、智能电网、电力数据和能源AI政策",
            "strategy": "候选政策源：重点过滤电力GIS、能源大数据、AI+能源和数字化政策",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "公安部政府信息公开",
        "url": "https://www.mps.gov.cn/",
        "base_url": "https://www.mps.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "公安改革、公共安全、科技信息化和社会治理政策动态",
            "strategy": "候选政策源：重点关注智慧公安、公安大数据、情指行和警用地理方向",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "住房和城乡建设部政策发布",
        "url": "https://www.mohurd.gov.cn/gongkai/zhengce/",
        "base_url": "https://www.mohurd.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "CIM、城市更新、智慧住建和城市治理相关政策",
            "strategy": "候选政策源：审核后按城市治理、CIM、实景三维和一张图关键词过滤",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "交通运输部政策公开",
        "url": "https://www.mot.gov.cn/zhengcejiedu/",
        "base_url": "https://www.mot.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "交通数字化、车路协同、运输治理和交通地图相关政策",
            "strategy": "候选政策源：重点关注车路协同、交通地图、位置智能和数据治理政策",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "中央网信办",
        "url": "https://www.cac.gov.cn/",
        "base_url": "https://www.cac.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "网络数据安全、数字中国、人工智能治理和数据合规政策",
            "strategy": "候选政策源：审核后只保留数据、AI治理、数字中国和安全合规相关内容",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "国家标准化管理委员会",
        "url": "https://www.sac.gov.cn/",
        "base_url": "https://www.sac.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "数据、地理信息、人工智能和城市治理相关标准动态",
            "strategy": "候选政策源：用于监控标准、指南、规范和技术门槛变化",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "中国政府网政策文件",
        "url": "https://www.gov.cn/zhengce/",
        "base_url": "https://www.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "国务院政策、部门文件和政策解读",
            "strategy": "候选政策源：按自然年和业务关键词筛选国家级政策信号",
        },
        "is_active": False,
    },
    # 市场候选源：行业动态、客户建设动态、区域市场信号。
    {
        "category": "news",
        "name": "中国信通院",
        "url": "https://www.caict.ac.cn/",
        "base_url": "https://www.caict.ac.cn",
        "selectors": {
            "type": "official_site",
            "scope": "数字经济、人工智能、数据治理、产业互联网研究动态",
            "strategy": "候选市场源：审核后低频采集，保留报告、白皮书和行业研究信号",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国地理信息产业协会",
        "url": "https://www.cagis.org.cn/",
        "base_url": "https://www.cagis.org.cn",
        "selectors": {
            "type": "official_site",
            "scope": "地理信息产业、GIS、测绘和空间数据行业动态",
            "strategy": "候选市场源：用于补充GIS、空间智能、地理信息产业趋势",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "泰伯网",
        "url": "https://www.taibo.cn/",
        "base_url": "https://www.taibo.cn",
        "selectors": {
            "type": "official_site",
            "scope": "地理信息、时空智能、数字孪生和自然资源行业资讯",
            "strategy": "候选市场源：用于监控行业案例、厂商动态和空间智能趋势",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "北极星电力网",
        "url": "https://news.bjx.com.cn/",
        "base_url": "https://news.bjx.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "电力数字化、电网调度、能源AI和智慧能源市场动态",
            "strategy": "候选市场源：只保留电力GIS、能源大数据、智能电网和AI相关内容",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "C114通信网",
        "url": "https://www.c114.com.cn/",
        "base_url": "https://www.c114.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "运营商、通信行业、算力网络和数字化转型动态",
            "strategy": "候选市场源：用于跟踪运营商数据、地图、AI和政企市场方向",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "国家电网公司新闻",
        "url": "https://www.sgcc.com.cn/html/sgcc_main/col2017021449/column_2017021449_1.shtml",
        "base_url": "https://www.sgcc.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "电网数字化、能源互联网、智能调度和电力数据动态",
            "strategy": "候选市场源：审核后低频采集央企电力数字化建设信号",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "南方电网新闻中心",
        "url": "https://www.csg.cn/xwzx/",
        "base_url": "https://www.csg.cn",
        "selectors": {
            "type": "official_site",
            "scope": "南网数字化、电力数据治理、智能电网和能源服务动态",
            "strategy": "候选市场源：审核后过滤电力数字化、数据治理和AI场景",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国移动新闻中心",
        "url": "https://www.chinamobileltd.com/sc/media/press.php",
        "base_url": "https://www.chinamobileltd.com",
        "selectors": {
            "type": "official_site",
            "scope": "运营商政企、算力网络、数据要素和AI应用动态",
            "strategy": "候选市场源：监控运营商政企数字化和AI业务方向",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国联通新闻中心",
        "url": "https://www.chinaunicom.com.cn/news/",
        "base_url": "https://www.chinaunicom.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "联通政企、数据智能、算力网络和行业应用动态",
            "strategy": "候选市场源：监控运营商数据、AI、智慧城市和行业解决方案方向",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国电信新闻中心",
        "url": "https://www.chinatelecom.com.cn/news/",
        "base_url": "https://www.chinatelecom.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "电信政企、云网融合、AI、数据和行业数字化动态",
            "strategy": "候选市场源：监控运营商云网、数据治理和AI行业方案",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "国家能源局新闻中心",
        "url": "https://www.nea.gov.cn/",
        "base_url": "https://www.nea.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "能源政策、能源数字化、智能电网、电力调度和行业建设动态",
            "strategy": "候选市场源：用于补充电力/能源数字化市场信号，按业务关键词过滤",
        },
        "is_active": False,
    },
    # 竞对候选源：默认不启用，审核后按中标/案例/产品/合作/区域动作分类。
    {
        "category": "competitor",
        "name": "吉奥时空/武大吉奥",
        "url": "https://www.geostar.com.cn/",
        "base_url": "https://www.geostar.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "武大吉奥/吉奥时空官网新闻、产品、方案、案例和区域动态",
            "strategy": "候选竞对源：重点监控时空大数据、智慧城市、自然资源和社会治理项目动作",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "京东与图/京图开放平台",
        "url": "https://lbsapi.jd.com/",
        "base_url": "https://www.jd-ex.com/",
        "selectors": {
            "type": "official_site",
            "scope": "京东地图、地址解析、物流位置服务和空间数据能力动态",
            "strategy": "候选竞对源：重点监控地址解析、围栏、路径规划、预分拣和企业地图服务",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "海致科技",
        "url": "https://www.haizhi.com/",
        "base_url": "https://www.haizhi.com",
        "selectors": {
            "type": "official_site",
            "scope": "海致官网新闻、产业级智能体、图计算、图谱和行业方案动态",
            "strategy": "候选竞对源：重点监控产业级智能体、图模融合、公共服务和能源金融场景",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "易智瑞 GeoScene",
        "url": "https://www.geoscene.cn/",
        "base_url": "https://www.geoscene.cn",
        "selectors": {
            "type": "official_site",
            "scope": "GeoScene平台、GIS产品、行业解决方案和生态动态",
            "strategy": "候选竞对源：重点监控国产GIS平台、空间分析、制图和位置智能能力",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "中科星图 GEOVIS",
        "url": "https://www.geovis.com.cn/",
        "base_url": "https://www.geovis.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "GEOVIS数字地球、空天信息、低空经济和遥感智能动态",
            "strategy": "候选竞对源：重点监控数字地球、自然资源、应急和低空经济解决方案",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "千寻位置",
        "url": "https://www.qxwz.com/",
        "base_url": "https://www.qxwz.com",
        "selectors": {
            "type": "official_site",
            "scope": "北斗高精度定位、时空智能、行业位置服务动态",
            "strategy": "候选竞对源：重点监控时空智能基础设施、定位服务和行业应用案例",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "四维图新",
        "url": "https://www.seewayai.com/",
        "base_url": "https://www.seewayai.com",
        "selectors": {
            "type": "official_site",
            "scope": "数字地图、位置大数据、智能驾驶和车联网方案动态",
            "strategy": "候选竞对源：重点监控地图数据、位置智能、车路协同和自动驾驶相关动作",
        },
        "is_active": False,
    },
    # 行业知识候选源：默认不启用，避免泛AI噪声。
    {
        "category": "ai",
        "name": "OpenAI News",
        "url": "https://openai.com/news/rss.xml",
        "selectors": {
            "type": "rss",
            "scope": "大模型、Agent、产品能力和安全治理更新",
            "strategy": "候选行业知识源：启用后只保留Agent、工具调用、多模态和企业应用相关内容",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "Google AI Blog",
        "url": "https://blog.google/technology/ai/rss/",
        "selectors": {
            "type": "rss",
            "scope": "Google AI、Gemini、地图/空间智能和模型应用动态",
            "strategy": "候选行业知识源：启用后过滤Agent、空间智能、多模态和企业应用内容",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "Microsoft AI Blog",
        "url": "https://blogs.microsoft.com/ai/feed/",
        "selectors": {
            "type": "rss",
            "scope": "企业AI、Copilot、Agent和云端智能应用动态",
            "strategy": "候选行业知识源：启用后过滤Agent Native、政企AI和行业智能体内容",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "Meta AI Blog",
        "url": "https://ai.meta.com/blog/rss/",
        "selectors": {
            "type": "rss",
            "scope": "开源模型、多模态、AI研究和工具生态动态",
            "strategy": "候选行业知识源：启用后过滤开源模型、Agent和多模态工程化内容",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "Hugging Face Blog",
        "url": "https://huggingface.co/blog/feed.xml",
        "selectors": {
            "type": "rss",
            "scope": "开源模型、推理、Agent框架和AI工程实践",
            "strategy": "候选行业知识源：启用后过滤Agent、RAG、模型部署和行业应用内容",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "arXiv cs.AI",
        "url": "https://rss.arxiv.org/rss/cs.AI",
        "selectors": {
            "type": "rss",
            "scope": "人工智能研究论文订阅源",
            "strategy": "候选行业知识源：启用后仅保留Agent、空间智能、多智能体和知识推理相关论文",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "arXiv cs.CL",
        "url": "https://rss.arxiv.org/rss/cs.CL",
        "selectors": {
            "type": "rss",
            "scope": "大语言模型、NLP和Agent相关论文订阅源",
            "strategy": "候选行业知识源：启用后过滤LLM、Agent、RAG和工具调用相关论文",
        },
        "is_active": False,
    },

    # 标讯/预算前置信号候选源：垂直行业平台和更早期采购意向。
    {
        "category": "bidding",
        "name": "中国铁塔电子采购平台",
        "url": "https://ebid.chinatowercom.cn/",
        "base_url": "https://ebid.chinatowercom.cn",
        "selectors": {
            "type": "browser",
            "scope": "中国铁塔采购公告、候选人公示、采购结果和预公示等",
            "strategy": "候选标讯源：需要渲染采集白名单；重点关注运营商站址、通信、电力、地图和数据治理项目",
            "risk_level": "high_js",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "中国政府采购网采购意向",
        "url": "https://www.ccgp.gov.cn/cgyx/",
        "base_url": "https://www.ccgp.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "政府采购意向公开，适合提前发现预算和建设方向",
            "strategy": "候选标讯源：低频采集采购意向，只保留公安、政数、自然资源、地址治理、空间智能和Agent相关方向",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "广东省公共资源交易平台",
        "url": "https://ygp.gdzwfw.gov.cn/",
        "base_url": "https://ygp.gdzwfw.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "广东公共资源交易公告、公示、结果和政府采购信息",
            "strategy": "候选标讯源：重点覆盖广东公安、政数、自然资源、城市治理和数据项目",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "深圳公共资源交易中心",
        "url": "https://www.szggzy.com/",
        "base_url": "https://www.szggzy.com",
        "selectors": {
            "type": "official_site",
            "scope": "深圳公共资源交易、政府采购、工程建设公告和结果",
            "strategy": "候选标讯源：重点关注深圳政务数据、城市治理、低空经济、AI和空间智能项目",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "bidding",
        "name": "广州公共资源交易中心",
        "url": "https://www.gzggzy.cn/",
        "base_url": "https://www.gzggzy.cn",
        "selectors": {
            "type": "official_site",
            "scope": "广州公共资源交易公告、公示和交易结果",
            "strategy": "候选标讯源：重点关注广州城市治理、公安信息化、实景三维和公共数据项目",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },

    # 政策/数据要素源：补充数据交易、公共数据授权运营和地方数据局窗口。
    {
        "category": "policy",
        "name": "财政部政府采购政策",
        "url": "https://gks.mof.gov.cn/guizhangzhidu/",
        "base_url": "https://gks.mof.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "政府采购、预算、采购政策和财政监管规则",
            "strategy": "候选政策源：低频采集政策规则，用于判断采购口径、预算方向和招采合规要求",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "上海数据交易所",
        "url": "https://www.chinadep.com/",
        "base_url": "https://www.chinadep.com",
        "selectors": {
            "type": "official_site",
            "scope": "数据要素流通、数据资产、数商生态和交易制度动态",
            "strategy": "候选政策源：低频采集数据要素市场政策和生态动态，服务公共数据授权运营判断",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "北京国际大数据交易所",
        "url": "https://www.bjidex.com/",
        "base_url": "https://www.bjidex.com",
        "selectors": {
            "type": "official_site",
            "scope": "北京数据交易、数据资产登记、数据流通和数商生态动态",
            "strategy": "候选政策源：监控数据资产登记、数据流通规则和高质量数据集建设方向",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "深圳数据交易所",
        "url": "https://datareg.szdex.com/",
        "base_url": "https://datareg.szdex.com",
        "selectors": {
            "type": "official_site",
            "scope": "深圳数据产权登记、数据公示、数据流通和跨境数据服务动态",
            "strategy": "候选政策源：监控数据产权登记、数据交易产品和地方数据要素制度创新",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "广东省政务服务和数据管理局",
        "url": "https://zfsg.gd.gov.cn/",
        "base_url": "https://zfsg.gd.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "广东政务服务、数字政府、公共数据和数据要素政策动态",
            "strategy": "候选政策源：按自然年采集广东数字政府和公共数据政策，服务重点区域市场判断",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "policy",
        "name": "浙江省数据局",
        "url": "https://dsj.zj.gov.cn/",
        "base_url": "https://dsj.zj.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "浙江数据局、数字政府、公共数据和数据要素相关政策动态",
            "strategy": "候选政策源：按自然年采集浙江数据和数字政府政策，关注一体化智能化公共数据平台方向",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },

    # 市场线索源：客户建设动态、行业会议、协会和产业窗口。
    {
        "category": "news",
        "name": "数字中国建设峰会",
        "url": "https://www.szzg.gov.cn/",
        "base_url": "https://www.szzg.gov.cn",
        "selectors": {
            "type": "official_site",
            "scope": "数字中国、数字政府、数据要素、数字福建和峰会成果动态",
            "strategy": "候选市场源：采集会议成果、地方样板和重点企业动作，提炼市场导向",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国国际大数据产业博览会",
        "url": "https://www.bigdata-expo.cn/",
        "base_url": "https://www.bigdata-expo.cn",
        "selectors": {
            "type": "official_site",
            "scope": "大数据、数据要素、产业数字化和政企合作活动动态",
            "strategy": "候选市场源：采集大会新闻、成果发布和签约方向，识别行业投资热点",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "世界人工智能大会",
        "url": "https://www.worldaic.com.cn/",
        "base_url": "https://www.worldaic.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "AI产业、模型生态、行业智能体、治理和企业应用动态",
            "strategy": "候选市场源：采集AI产业趋势和政企落地案例，过滤泛消费AI新闻",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "中国测绘学会",
        "url": "https://www.csgpc.org/",
        "base_url": "https://www.csgpc.org",
        "selectors": {
            "type": "official_site",
            "scope": "测绘地理信息、空间数据、时空智能和行业标准活动动态",
            "strategy": "候选市场源：用于补充测绘地信、空间智能和行业标准趋势",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "移动云新闻中心",
        "url": "https://ecloud.10086.cn/home/about/news",
        "base_url": "https://ecloud.10086.cn",
        "selectors": {
            "type": "browser",
            "scope": "移动云、政企云、算力网络、AI和行业解决方案动态",
            "strategy": "候选市场源：需要渲染采集白名单；重点监控运营商政企AI和数据能力",
            "risk_level": "high_js",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "天翼云新闻中心",
        "url": "https://www.ctyun.cn/portal/news",
        "base_url": "https://www.ctyun.cn",
        "selectors": {
            "type": "browser",
            "scope": "天翼云、云网融合、政企AI、数据治理和行业云动态",
            "strategy": "候选市场源：需要渲染采集白名单；重点监控电信政企和数据智能方案",
            "risk_level": "high_js",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "联通数科",
        "url": "https://www.chinaunicomdigital.com/",
        "base_url": "https://www.chinaunicomdigital.com",
        "selectors": {
            "type": "official_site",
            "scope": "联通数科、数字政府、数据智能、智慧城市和行业应用动态",
            "strategy": "候选市场源：监控运营商数据、AI、智慧城市和行业解决方案方向",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "news",
        "name": "国网数科",
        "url": "https://www.sgcc.com.cn/",
        "base_url": "https://www.sgcc.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "国家电网数字化、能源互联网、数据治理和电力AI生态动态",
            "strategy": "候选市场源：作为电力数字化主题入口，启用前需确认稳定栏目",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },

    # 竞对源：补齐GIS、位置服务、云厂商城市智能和地址能力竞品。
    {
        "category": "competitor",
        "name": "苍穹数码",
        "url": "https://www.kqgeo.com/",
        "base_url": "https://www.kqgeo.com",
        "selectors": {
            "type": "official_site",
            "scope": "苍穹KQGIS、自然资源、地籍调查、国产GIS和空间信息平台动态",
            "strategy": "候选竞对源：监控国产GIS平台、自然资源方案、信创适配和产品发布",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "正元地信",
        "url": "https://www.geniuses.com.cn/",
        "base_url": "https://www.geniuses.com.cn",
        "selectors": {
            "type": "official_site",
            "scope": "正元地信、智慧城市、地下管网、测绘地理信息和数据服务动态",
            "strategy": "候选竞对源：监控智慧城市、地下空间、测绘和城市运营服务动作",
            "risk_level": "normal_public",
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "百度地图开放平台",
        "url": "https://lbsyun.baidu.com/",
        "base_url": "https://lbsyun.baidu.com",
        "selectors": {
            "type": "direct_pages",
            "scope": "百度地图开放平台、地址解析、路线规划、位置智能和企业地图能力",
            "strategy": "候选竞对源：直采能力页，监控地址解析、路径规划、位置智能和企业地图能力变化",
            "risk_level": "medium_js",
            "pages": [
                {"name": "百度地图开放平台", "url": "https://lbsyun.baidu.com/"},
            ],
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "高德开放平台",
        "url": "https://lbs.amap.com/",
        "base_url": "https://lbs.amap.com",
        "selectors": {
            "type": "direct_pages",
            "scope": "高德开放平台、地图API、地理编码、路径规划和位置服务能力",
            "strategy": "候选竞对源：直采能力页，监控地理编码、地图API、路径规划和行业方案变化",
            "risk_level": "medium_js",
            "pages": [
                {"name": "高德开放平台", "url": "https://lbs.amap.com/"},
            ],
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "腾讯位置服务",
        "url": "https://lbs.qq.com/",
        "base_url": "https://lbs.qq.com",
        "selectors": {
            "type": "direct_pages",
            "scope": "腾讯位置服务、地图开放平台、路线规划、地点搜索和位置大数据能力",
            "strategy": "候选竞对源：直采能力页，监控位置服务、位置大数据和行业解决方案变化",
            "risk_level": "medium_js",
            "pages": [
                {"name": "腾讯位置服务", "url": "https://lbs.qq.com/"},
            ],
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "华为云城市智能体",
        "url": "https://www.huaweicloud.com/solution/city.html",
        "base_url": "https://www.huaweicloud.com",
        "selectors": {
            "type": "direct_pages",
            "scope": "华为云城市智能体、智慧城市、城市治理和政务云方案",
            "strategy": "候选竞对源：直采方案页，监控城市智能体、政务云和行业AI方案变化",
            "risk_level": "medium_js",
            "pages": [
                {"name": "华为云城市智能体", "url": "https://www.huaweicloud.com/solution/city.html"},
            ],
        },
        "is_active": False,
    },
    {
        "category": "competitor",
        "name": "阿里云城市大脑",
        "url": "https://www.aliyun.com/solution/citybrain",
        "base_url": "https://www.aliyun.com",
        "selectors": {
            "type": "direct_pages",
            "scope": "阿里云城市大脑、数字政府、数据智能和城市治理方案",
            "strategy": "候选竞对源：直采方案页，监控城市大脑、政务数据和城市治理能力变化",
            "risk_level": "medium_js",
            "pages": [
                {"name": "阿里云城市大脑", "url": "https://www.aliyun.com/solution/citybrain"},
            ],
        },
        "is_active": False,
    },

    # 行业知识源：补Agent工程化、空间智能、AI治理和企业应用。
    {
        "category": "ai",
        "name": "Anthropic News",
        "url": "https://www.anthropic.com/news/rss.xml",
        "selectors": {
            "type": "rss",
            "scope": "Claude、Agent、安全治理、企业AI和模型能力更新",
            "strategy": "候选行业知识源：启用后只保留Agent、安全治理、企业应用和模型能力相关内容",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "LangChain Blog",
        "url": "https://blog.langchain.com/rss/",
        "selectors": {
            "type": "rss",
            "scope": "Agent框架、工具调用、RAG、LangGraph和企业级AI应用实践",
            "strategy": "候选行业知识源：启用后过滤Agent编排、工具调用、RAG和工程化实践内容",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "LlamaIndex Blog",
        "url": "https://www.llamaindex.ai/blog/rss.xml",
        "selectors": {
            "type": "rss",
            "scope": "RAG、数据Agent、知识库、企业数据连接和检索增强实践",
            "strategy": "候选行业知识源：启用后过滤RAG、数据Agent、知识库和企业数据治理实践",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "NVIDIA Technical Blog",
        "url": "https://developer.nvidia.com/blog/feed/",
        "selectors": {
            "type": "rss",
            "scope": "GPU、推理加速、数字孪生、机器人、边缘AI和企业AI工程实践",
            "strategy": "候选行业知识源：启用后过滤推理部署、边缘AI、数字孪生和行业AI内容",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "OGC News",
        "url": "https://www.ogc.org/newsroom/feed/",
        "selectors": {
            "type": "rss",
            "scope": "开放地理空间标准、OGC生态、空间数据互操作和行业标准动态",
            "strategy": "候选行业知识源：启用后过滤空间标准、地理数据互操作和数字孪生相关内容",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "Esri Blog",
        "url": "https://www.esri.com/arcgis-blog/feed/?post_type=blog",
        "selectors": {
            "type": "rss",
            "scope": "GIS、空间分析、数字孪生、地图平台和位置智能实践",
            "strategy": "候选行业知识源：启用后过滤空间智能、GIS平台、数字孪生和行业案例",
            "risk_level": "rss_low",
        },
        "is_active": False,
    },
    {
        "category": "ai",
        "name": "OSGeo Foundation News",
        "url": "https://www.osgeo.org/foundation-news/feed/",
        "selectors": {
            "type": "rss",
            "scope": "开源 GIS、GDAL/PROJ、地理空间软件生态、空间数据工程和开源标准动态",
            "strategy": "行业知识源：订阅解析，过滤空间数据、GIS平台、地理空间软件和AI+地理空间工程实践",
            "risk_level": "rss_low",
            "knowledge_domain": "spatial",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "QGIS.org Blog",
        "url": "https://blog.qgis.org/feed/",
        "selectors": {
            "type": "rss",
            "scope": "QGIS、开源GIS桌面平台、空间分析、插件生态和地理空间工程实践",
            "strategy": "行业知识源：订阅解析，沉淀开源GIS平台、空间分析和数据生产相关素材",
            "risk_level": "rss_low",
            "knowledge_domain": "spatial",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "OpenStreetMap Blog",
        "url": "https://blog.openstreetmap.org/feed/",
        "selectors": {
            "type": "rss",
            "scope": "OpenStreetMap、众源地图、地理数据生态、地图社区和位置数据治理动态",
            "strategy": "行业知识源：订阅解析，补充地图底图、众源地理数据、地址和POI生态知识",
            "risk_level": "rss_low",
            "knowledge_domain": "spatial",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "GeoServer Blog",
        "url": "https://geoserver.org/feed.xml",
        "selectors": {
            "type": "rss",
            "scope": "GeoServer、OGC服务、空间数据发布、地图服务和地理空间平台工程实践",
            "strategy": "行业知识源：订阅解析，沉淀地图服务、OGC标准和空间数据服务工程素材",
            "risk_level": "rss_low",
            "knowledge_domain": "spatial",
        },
        "is_active": True,
    },
    {
        "category": "ai",
        "name": "GeoTools Blog",
        "url": "https://geotoolsnews.blogspot.com/feeds/posts/default",
        "selectors": {
            "type": "rss",
            "scope": "GeoTools、Java GIS工具链、地理空间数据处理、OGC标准和空间数据工程",
            "strategy": "行业知识源：订阅解析，补充空间数据处理、GIS服务开发和标准适配知识",
            "risk_level": "rss_low",
            "knowledge_domain": "spatial",
        },
        "is_active": True,
    },
])


PUBLIC_LIST_SELECTORS: dict[str, Any] = {
    "type": "official_site",
    "list": "li, tr, .list li, .news-list li, .article-list li, .list-item, article",
    "title": "a",
    "link": "a@href",
    "date": "time, .date, .time, .rq, span",
}

BIDDING_PUBLIC_LIST_SELECTORS: dict[str, Any] = {
    "type": "official_site",
    "list": "a",
    "title": "a",
    "link": "a@href",
    "date": "time, .date, .time, .rq, span",
}

COMPETITOR_LIST_SELECTORS: dict[str, Any] = {
    "type": "official_site",
    "list": "li, .news-list li, .article-list li, .list li, .item, article",
    "title": "a",
    "link": "a@href",
    "date": "time, .date, .time, span",
}

